import { Metadata } from "next";
import Container from "@/components/layout/Container";

export const metadata: Metadata = {
  title: "Terms of Service - Jumpytools",
  description: "Terms of Service for Jumpytools",
};

export default function TermsOfService() {
  return (
    <Container className="py-12 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      
      <div className="prose prose-sm sm:prose-base dark:prose-invert max-w-none space-y-6">
        <p><strong>Last Updated: July 23, 2026</strong></p>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing and using Jumpytools (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">2. Description of Service</h2>
          <p>
            Jumpytools provides a collection of online utilities for developers, designers, and general users. The Service is provided "as is" and "as available". We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">3. User Responsibilities</h2>
          <p>
            You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, overburden, or impair the Service. 
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">4. No Warranties</h2>
          <p>
            While we strive for accuracy, we make no guarantees regarding the reliability, correctness, or completeness of the tools provided. You use the tools entirely at your own risk. We are not responsible for any data loss, financial loss, or other damages resulting from the use of our Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">5. Intellectual Property</h2>
          <p>
            The tools, design, and content of Jumpytools are the property of Jumpytools. You may use the output generated by our tools for personal and commercial purposes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">6. Third-Party Links and Ads</h2>
          <p>
            Our Service may contain links to third-party web sites or services that are not owned or controlled by us. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party web sites or services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">7. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms of Service.
          </p>
        </section>
      </div>
    </Container>
  );
}
