export const certificateCategories: Record<string, string[]> = {
  Education: [
    'Achievement Certificate',
    'Academic Excellence Certificate',
    'Merit Certificate',
    'Excellence in Subject Certificate',
    'Perfect Attendance Certificate',
    'Outstanding Performance Certificate',
    'Student of the Month Certificate',
    'Most Improved Student Certificate',
    'Best Project Certificate',
    'Best Presentation Certificate',
    'Reading Achievement Certificate',
    'Writing Achievement Certificate',
    'Mathematics Excellence Certificate',
    'Science Excellence Certificate',
    'Computer Excellence Certificate',
    'Language Proficiency Certificate',
  ],
  Competition: [
    'First Prize Certificate',
    'Second Prize Certificate',
    'Third Prize Certificate',
    'Winner Certificate',
    'Runner-up Certificate',
    'Participation Certificate',
    'Quiz Competition Certificate',
    'Debate Competition Certificate',
    'Essay Writing Certificate',
    'Drawing Competition Certificate',
    'Science Fair Certificate',
    'Hackathon Certificate',
    'Coding Competition Certificate',
    'Chess Competition Certificate',
    'Sports Competition Certificate',
  ],
  'School & College': [
    'Course Completion Certificate',
    'Training Completion Certificate',
    'Workshop Participation Certificate',
    'Seminar Participation Certificate',
    'Internship Completion Certificate',
    'Volunteer Certificate',
    'Leadership Certificate',
    'Club Membership Certificate',
    'Student Ambassador Certificate',
  ],
  Corporate: [
    'Employee of the Month',
    'Employee Recognition Certificate',
    'Appreciation Certificate',
    'Outstanding Performance Certificate',
    'Years of Service Certificate',
    'Training Completion Certificate',
    'Team Excellence Award',
    'Leadership Award',
    'Innovation Award',
  ],
  Appreciation: [
    'Certificate of Appreciation',
    'Certificate of Recognition',
    'Thank You Certificate',
    'Volunteer Appreciation Certificate',
    'Mentor Appreciation Certificate',
    'Teacher Appreciation Certificate',
    'Guest Speaker Appreciation Certificate',
    'Sponsor Appreciation Certificate',
  ],
  Events: [
    'Event Participation Certificate',
    'Organizing Committee Certificate',
    'Speaker Certificate',
    'Judge Certificate',
    'Volunteer Certificate',
    'Cultural Event Certificate',
    'Music Competition Certificate',
    'Dance Competition Certificate',
  ],
  Sports: [
    'Champion Certificate',
    'Participation Certificate',
    'Best Player Award',
    'MVP Certificate',
    'Fair Play Award',
    'Sportsmanship Award',
    'Coach Appreciation Certificate',
  ],
  'Online Learning': [
    'Online Course Completion',
    'Bootcamp Completion',
    'Webinar Attendance',
    'Certification of Skills',
    'Learning Achievement',
  ],
};

export const TOOL_METADATA = {
  title: 'Certificate Generator',
  description: 'Design and generate custom certificates of achievement instantly. Download as high-quality PNG or PDF.',
  slug: 'certificate-generator',
  category: 'design-color',
};

export const TOOL_FAQS = [
  {
    question: 'How can I download the generated certificate?',
    answer: 'You can download the generated certificate directly as a high-quality PNG image or trigger a print window to save it as a landscape PDF.',
  },
];

export const TOOL_ABOUT = [
  'Certificate Generator is a versatile utility to design certificates of achievement for online courses, workshops, corporate recognition, and competitive events.',
];
