export const DEFAULT_SPACES = 2;
export const MAX_JSON_SIZE = 500000;

export const TOOL_METADATA = {
  title: 'JSON Formatter / Validator',
  description: 'Format, validate, and minify raw JSON string data. Prettify with customizable tab indentation levels and inspect nodes in a collapsible tree explorer.',
  slug: 'json-formatter',
  category: 'developer-tools',
  fullWidth: true,
};

export const TOOL_FAQS = [
  {
    question: 'Is my JSON data secure on this website?',
    answer: 'Yes — all processing happens entirely in your browser. Your data never leaves your device and is not sent to any server.',
  },
  {
    question: 'How do I format JSON with custom indentation?',
    answer: 'Use the "Spaces" dropdown in the toolbar to select your preferred indentation level (2, 4, or 8 spaces), then click "Prettify JSON".',
  },
  {
    question: 'Can this tool handle invalid JSON?',
    answer: 'The formatter will detect invalid JSON and show a descriptive error message below the input area. The Format and Minify buttons are disabled until the input is valid.',
  },
];

export const TOOL_ABOUT = [
  'JSON (JavaScript Object Notation) is a lightweight, text-based data-interchange format. It is easy for humans to read and write and easy for machines to parse and generate. However, raw JSON generated by APIs is often minified into a single line, making it hard to inspect.',
  'Features of this Formatter:',
  '• Format minified JSON to make it human-readable.',
  '• Minify formatted JSON to compress space for API requests.',
  '• Validate JSON strings to ensure correctness of keys, quotes, and commas.',
  '• One-click copy to clipboard.',
  'Ensure your JSON conforms to standard specifications: string keys must be surrounded by double quotes, and trailing commas are not allowed.',
];
